# Test Project for IA Nuxt replacement
# See https://earthly.dev/blog/setup-reverse-proxy-kubernetes-nginx/
# and #302354 for Details
import os
from flask import Flask, request

app = Flask(__name__)


@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def hello_world(path):
    content = f'''Hello from {os.getenv("HELLO_NAME", "Flask")}, serving <a href={request.url}>{request.url}</a>!</br>
This is just a test-page, generated by <a href=https://github.com/The-Judge/flask-greeter>https://github.com/The-Judge/flask-greeter</a></br>
Feel free to leave star if you think this is useful 🫶</br>'''
    return content


if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0')
